### ISSUE TITLE
华工师兄，能了解下导师吗？

### ISSUE THREAD

**Issue by upsx** [YSunLIN/SIMT_TC#1]

**Comment by YSunLIN** [comment]
对于我这边的导师，如果你想天天做项目，被剥削，没人带，无发论文时间，那还是可以考虑的。

**Comment by Tim-Sx** [comment]
15626292797这是我微信，能加一下吗？

**Comment by Tim-Sx** [comment]
> 对于我这边的导师，如果你想天天做项目，被剥削，没人带，无发论文时间，那还是可以考虑的。

15626292797这是我微信，能加一下吗？
